version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: shcbot-web:latest
    container_name: shcbot-web-1
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
