services:
  web:
    build: ./app
    platform: linux/arm64
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "production"
      AI_API_URL: "http://ai:8000"
    links:
      - ai
    restart: always

  ai:
    build: ./ai
    platform: linux/arm64
    ports:
      - "8000:8000"
    volumes:
      - vector_storage:/app/.vector_storage
      - pdf_data:/app/data/PDF
      - markdown_data:/app/data/Markdown
    environment:
      DB_DIRECTORY: /app/.vector_storage
      DATA_DIRECTORY: /app/data
    restart: always

  scraper:
    build: ./scraper
    platform: linux/arm64
    volumes:
      - pdf_data:/app/PDF
      - markdown_data:/app/Markdown
    restart: always

volumes:
  vector_storage:
  pdf_data:
  markdown_data:
  tei_model_data:
